spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/dcloud
    url: jdbc:mysql://${DCLOUD_BUCKET_ENDPOINT}/dcloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    username: sa
    username: ${MYSQL_USERNAME}
#    password:
    password: ${MYSQL_PASSWORD}
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  h2:
    console:
      enabled: true
  redis:
    port: 6379
    host: localhost
jwt:
  secret: testtesttesttesttesttesttesttest
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

cloud:
  aws:
    stack:
      auto: false